---
title: "Directly labeling ggdist lineribbons with geomtextpath"
description: |
  Directly labeling {ggdist} lineribbons with {geomtextpath}.
author:
  - name: Michael McCarthy
date: 2022-10-29
categories:
  - .Visualize
  - "{ggdist}"
  - "{geomtextpath}"
repository_url: https://github.com/mccarthy-m-g/tidytales

output:
  distill::distill_article:
    self_contained: false
    toc: true
---

```{r setup, include=FALSE}
# Set default options for knitr code chunks -----------------------------------
knitr::opts_chunk$set(comment = "#>",
                      echo = TRUE)

# Create templates for knitr code chunks --------------------------------------
knitr::opts_template$set(
  fig.graphic = list(echo = FALSE),
  no.message = list(message = FALSE, warning = FALSE)
)
```

## Prerequisites

To access the datasets, help pages, and functions that we will use in this code snippet, load the following packages:

```{r prerequisite-packages, opts.label="no.message"}
library(tidyverse)
library(ggdist)
library(geomtextpath)
```

## Directly labeling lineribbons

First make some data.

```{r}
set.seed(1234)
n = 5000

df <- tibble(
  .draw = 1:n,
  intercept = rnorm(n, 3, 1),
  slope = rnorm(n, 1, 0.25),
  x = list(-4:5),
  y = map2(intercept, slope, ~ .x + .y * -4:5)
) %>%
  unnest(c(x, y))
```

Then plot it.

```{r}
df %>%
  group_by(x) %>%
  median_qi(y, .width = c(.50, .80, .95)) %>%
  ggplot(aes(x = x, y = y, ymin = .lower, ymax = .upper)) +
  # Hide the line from geom_lineribbon() by setting `size = 0`
  geom_lineribbon(size = 0) +
  scale_fill_brewer() +
  # Replace the hidden line with a labelled line
  geom_textline(label = "label")
```
